---
meta:
  - environment_name: 'testing'
  - schema_version: '0.1'
network:
  - network_cidr: '10.80.0.0/16'
deployments:
  - deployment_name: 'TSM Provision Test 1'
    deployment_runtime_file: '_deployments.yml'
    deployment_href: 'runtime'
    servers:
    - server_name: 'Web API 1'
      server_tag: 'WEB_API'
      server_cloud_id: '2'
      server_instance_type: 'm1.small'
      server_template: 'Linux MCI v1'
      server_ssh_key_uid: 'tsmkey01'
      server_subnet_uid: 'subnet-4484782e'
      server_subnet_href: '/api/clouds/2/subnets/7OFIS9S4A3690'
      server_security_group_uid: 'sg-2946b046'
      server_runtime_file: '_servers.yml'
      server_inputs:
        - GROUP: 'text:com.msm.web'
          TARGET: 'text:public-rest-api'
          VERSION: 'text:1.0'
          SNAPSHOT: 'text:true'
          SNAPSHOT_TIMESTAMP: 'text:20131003.181100-32'
          JVM_ARGS: 'text:-server'
          KAFKA_SERVICE_IP: 'text:54.220.226.38'
          REDIS_MASTER_IP: 'text:54.217.114.151'
          HELLOTEXT: 'Server created by right_api_client'
    - server_name: 'Agg API 1'
      server_tag: 'AGGREGATOR_API'
      server_cloud_id: '2'
      server_instance_type: 'm1.small'
      server_template: 'Linux MCI v1'
      server_ssh_key_uid: 'tsmkey01'
      server_subnet_uid: 'subnet-4484782e'
      server_subnet_href: '/api/clouds/2/subnets/7OFIS9S4A3690'
      server_security_group_uid: 'sg-2b46b044'
      server_runtime_file: '_servers.yml'
      server_inputs:
        - GROUP: 'text:com.msm.aggregator'
          TARGET: 'text:rest-api'
          VERSION: 'text:1.0'
          SNAPSHOT: 'text:true'
          SNAPSHOT_TIMESTAMP: 'text:20131008.104711-72'
          JVM_ARGS: 'text:-Dhttp.client.proxy.enabled=true -Dhttp.client.proxy.address=46.51.161.26 -Dhttp.client.proxy.port=80 -Dkafka-metering.enabled=true -server'
          KAFKA_SERVICE_IP: 'text:54.220.226.38'
          REDIS_MASTER_IP: 'text:54.217.114.151'
          MONGO_MASTER_IP: 'text:46.137.31.91'
          HELLOTEXT: 'Server created by right_api_client'
    server_arrays:
    - server_array_name: 'My New Server Array 1'
      server_array_cloud_id: '2'
      server_array_size: 'm1.small'
