---
cloud:
  - cloud_id: '2'
network:
  - network_cidr: '10.80.0.0/16'
deployments:
  - deployment_name: 'TSM Provision Test 1'
    deployment_runtime_file: '_deployments.yml'
  - servers:
    - server_name: 'My New Server 1'
      server_cloud_id: '2'
      server_size: 'm1.small'
      server_template: 'Linux MCI v1'
      server_runtime_file: '_servers.yml'
      server_inputs:
        - input1: 'text:value'
          input2: 'text:value'
    - server_name: 'My New Server 2'
      server_cloud_id: '2'
      server_size: 'm1.small'
      server_template: 'Linux MCI v1'
      server_runtime_file: '_servers.yml'
      server_inputs:
      - input1: 'text:value'
        input2: 'text:value'
  - server_arrays:
    - server_array_name: 'My New Server Array 1'
      server_cloud_id: '2'
      server_array_size: 'm1.small'
